import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import solc from 'solc';

export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dependencyRoots = [
  path.join(root, 'node_modules'),
  path.resolve(root, '..', 'node_modules'),
];

function resolveDependency(name) {
  const normalized = name.replaceAll('\\', '/');
  if (path.isAbsolute(name) || normalized.split('/').includes('..')) return null;
  for (const dependencyRoot of dependencyRoots) {
    const candidate = path.resolve(dependencyRoot, normalized);
    if (candidate.startsWith(dependencyRoot + path.sep) && fs.existsSync(candidate)) return candidate;
  }
  return null;
}

function readSource(file) {
  return fs.readFileSync(file, 'utf8').replaceAll('\r\n', '\n');
}

export function compile({ quiet = false } = {}) {
  const sources = {};
  function collect(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const absolute = path.join(dir, entry.name);
      if (entry.isDirectory()) collect(absolute);
      else if (entry.name.endsWith('.sol')) {
        sources[path.relative(root, absolute).replaceAll('\\', '/')] = {
          content: readSource(absolute),
        };
      }
    }
  }
  collect(path.join(root, 'contracts'));
  const input = {
    language: 'Solidity', sources,
    settings: {
      optimizer: { enabled: true, runs: 200 },
      viaIR: true,
      evmVersion: 'shanghai',
      outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object', 'metadata'] } },
    },
  };
  const output = JSON.parse(solc.compile(JSON.stringify(input), {
    import: name => {
      const file = resolveDependency(name);
      return file
        ? { contents: readSource(file) }
        : { error: `Import not found: ${name}` };
    },
  }));
  for (const error of output.errors ?? []) {
    if (error.severity === 'error' || !quiet) console.error(error.formattedMessage);
  }
  if (output.errors?.some(error => error.severity === 'error')) throw new Error('Solidity compilation failed');
  const artifacts = {};
  fs.mkdirSync(path.join(root, 'artifacts'), { recursive: true });
  fs.mkdirSync(path.join(root, 'integration'), { recursive: true });
  const verificationSources = { ...sources };
  for (const name of Object.keys(output.sources)) {
    if (!verificationSources[name]) {
      const file = resolveDependency(name);
      if (!file) throw new Error(`Compiled dependency not found: ${name}`);
      verificationSources[name] = { content: readSource(file) };
    }
  }
  fs.writeFileSync(path.join(root, 'artifacts', 'standard-input.json'),
    JSON.stringify({ ...input, sources: verificationSources }, null, 2) + '\n');
  for (const [sourceName, contracts] of Object.entries(output.contracts)) {
    if (!sourceName.startsWith('contracts/')) continue;
    for (const [contractName, result] of Object.entries(contracts)) {
      if (!result.evm.bytecode.object) continue;
      const artifact = {
        contractName, sourceName, compiler: solc.version(), evmVersion: 'shanghai',
        abi: result.abi, bytecode: '0x' + result.evm.bytecode.object,
        deployedBytecode: '0x' + result.evm.deployedBytecode.object,
        metadata: JSON.parse(result.metadata),
      };
      artifacts[contractName] = artifact;
      fs.writeFileSync(path.join(root, 'artifacts', contractName + '.json'), JSON.stringify(artifact, null, 2) + '\n');
      fs.writeFileSync(path.join(root, 'artifacts', contractName + '.abi.json'), JSON.stringify(result.abi, null, 2) + '\n');
      const bytes = result.evm.deployedBytecode.object.length / 2;
      if (bytes > 24576) throw new Error(`${contractName} exceeds EVM runtime size limit`);
      if (!quiet) console.log(`${contractName}: compiled; runtime ${bytes} bytes`);
    }
  }
  fs.writeFileSync(path.join(root, 'integration', 'abi.ts'),
    '// Generated by npm run compile; do not edit.\nexport const aegisAbi = ' +
    JSON.stringify(artifacts.AegisPermissions.abi, null, 2) + ' as const;\n');
  return artifacts;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) compile();
